defaults:
  - contrastive_context.yaml

name: "same"

train_sampler:
  thetas: [0., 3.141]
  phis: [0., 6.283]
  r_mu: 0.  # in mu
  h_mu: 0.  # in mu
  exclude_self: False

val_sampler:
  thetas: [0., 3.141]
  phis: [0., 6.283]
  r_mu: 0.  # in mu
  h_mu: 0.  # in mu
  exclude_self: False
