defaults:
  - default.yaml

num_nodes: 1
accelerator: gpu
devices: 4
strategy:
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: False
sync_batchnorm: True
use_distributed_sampler: False  # Should be set to False if using own distributed sampler
