_target_: pytorch_lightning.Trainer

gpus: 0

max_epochs: 400

replace_sampler_ddp: False
log_every_n_steps: 1

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
