_target_: pytorch_lightning.Trainer

max_epochs: 400

log_every_n_steps: 4

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
