# @package _global_

# runs with execution time profiling

defaults:
  - override /log_dir: debug.yaml

trainer:
  max_epochs: 1
  profiler: "simple"
  #profiler:
  #  _target_: pytorch_lightning.profilers.PyTorchProfiler
  #  filename: profile_log
  # profiler: "advanced"
  # profiler: "pytorch"
